[build]
builder = "nixpacks"

[variables]
HF_HUB_ENABLE_HF_TRANSFER = "1"
SENTENCE_TRANSFORMERS_HOME = "/tmp/.cache"
PYTHONPATH = "/BACKEND"

[deploy]
rootDirectory = "BACKEND"
startCommand = "python -m uvicorn app.api:app --host 0.0.0.0 --port $PORT"
